title: Shanno's Blog
description: My Personal Stack Problems
author: ^v^
github: https://github.com/wuxiangwei
about: 知行合一 止于至善
disqus_shortname:
google_analytics:
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/wuxiangwei"

urls:
    - text: About Me
      url: /about/
#     - text: My Projects
#       url: /projects/
#     - text: XML Feed
#       url: /feed.xml

url: "https://wuxiangwei.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
